### ISSUE TITLE
Consider eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by sanoodles** [valtech-ch/eslint-config#4]
https://www.npmjs.com/package/eslint-plugin-simple-import-sort

Pros i can see, inline with discussed:

* Quickly understand what is used in your components, specially speeding up onboarding of new developers to projects where the origin of imports is not homogeneous/easily predictable

**Comment by lorenzogm** [comment]
Sounds great, thanks for suggesting it. Could you create a PR to add it?
